name: Generate Images JSON

on:
  push:
    branches:
      - main
    # Only trigger on new/changed photograph files in images/
    paths:
      - 'images/**/*.jpg'
      - 'images/**/*.jpeg'
      - 'images/**/*.png'
      - 'images/**/*.gif'
      - 'images/**/*.webp'
      - 'images/**/*.bmp'
      - 'images/**/*.tiff'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate-images-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install Pillow geopy piexif gpxpy pandas

      - name: Generate images.json
        run: |
          python index_and_enrich.py

      - name: Check for changes
        id: check_changes
        run: |
          git diff --exit-code images.json || echo "changed=true" >> $GITHUB_OUTPUT

      - name: Commit and push changes
        if: steps.check_changes.outputs.changed == 'true'
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add images.json
          git commit -m "Auto-generate images.json from images/ directory"
          git push